<a href="https://colab.research.google.com/github/aartinangare1745/Assignment-2/blob/main/numpy_50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [ ]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.version)
np.show_config

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>


<function numpy.__config__.show(mode='stdout')>

In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#### 4. How to find the memory size of any array (★☆☆)
a = np.zeros((10,10))
memory_size=a.size*a.itemsize
memory_size

800

In [ ]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
a=[]
for i in range(10,50):
  a.append(i)
np.array(a)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:

#### 8. Reverse a vector (first element becomes last) (★☆☆)
a=[1,2,3,4]  #rev=[4,3,2,1]
b=a[::-1]
b

[4, 3, 2, 1]

In [ ]:
#reversed loop
rev=[]
for i in range(len(a)-1,-1,-1):
  rev.append(a[i])
rev

[4, 3, 2, 1]

In [ ]:
#reversed()
for ele in reversed(a):
  print(ele)

4
3
2
1


In [ ]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
arr=[1,2,0,0,4,0]
l=[i for i in range(len(arr)) if arr[i]!=0]
l

[0, 1, 4]

In [ ]:
#### 11. Create a 3x3 identity matrix (★☆☆)
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.info(np.eye)
b=np.identity(3)
b

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
import numpy as np
arr = np.random.randint(0, 100, size=(3,3,3))
print(arr)

[[[32 22 85]
  [92 25 65]
  [78 80 44]]

 [[98 20 14]
  [23 86 12]
  [29 67 13]]

 [[71 92 31]
  [ 2 41 18]
  [37 82 93]]]


In [3]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values
z=np.random.random((10,10)) # This line creates a 10x10 NumPy array (a grid of 10 rows and 10 columns) and fills it with random floating-point numbers between 0.0 (inclusive) and 1.0 (exclusive).
print(z.min(),z.max()) # This line then prints the smallest (minimum) value and the largest (maximum) value found within the array 'z'.

0.02186118285708627 0.9942395104888834


In [4]:
#14. Create a random vector of size 30 and find the mean value
vec=np.random.random(30)
mee=vec.mean()
mee

np.float64(0.5628160683440822)

In [5]:
### 15. Create a 2d array with 1 on the border and 0 inside
arr=np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [10]:
print(np.nan==np.nan)

False


In [11]:
0*np.nan

nan

In [13]:
np.inf>np.nan

False

In [14]:
np.nan-np.nan

nan

In [15]:
np.nan in set([np.nan])

True

In [17]:
0.3==3*0.1

False

In [21]:

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [23]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern
arr=np.zeros((8,8),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [24]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

In [28]:
#### 21. Create a checkerboard 8x8 matrix using the tile function
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [29]:
#### 22. Normalize a 5x5 random matrix
arr=np.random.random((5,5))

norm=(arr-np.mean(arr))/np.std(arr)
norm

array([[-0.90788502,  1.43602491, -0.56270563, -1.2365841 , -0.90763559],
       [ 1.83869552, -0.29982735,  0.12626948,  0.25239596,  0.86831809],
       [-0.21322484,  0.15910353, -0.9703919 , -0.0153342 ,  0.71859834],
       [ 1.69586509, -1.07619546, -0.59860935, -0.50375662, -0.90673341],
       [-1.2128317 ,  1.2510312 ,  1.69830059,  0.6889554 , -1.32184294]])

In [30]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color=np.dtype([
    ('r',np.ubyte),
    ('g',np.ubyte),
    ('b',np.ubyte),
    ('a',np.ubyte)
])
clr

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [31]:
### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a=np.ones((5,3))
b=np.ones((3,2))
pro=np.matmul(a,b)
pro

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [32]:
a@b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [34]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
arr=np.arange(11)
arr[(arr>3)&(arr<8)]*=-1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [35]:
#### 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [38]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z
#2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [40]:
#### 28. What are the result of the following expressions? (★☆☆)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/tmp/ipykernel_4454/4024135768.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_4454/4024135768.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_4454/4024135768.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [41]:
#### 29. How to round away from zero a float array ?
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [42]:
#### 30. How to find common values between two arrays? (★☆☆)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 6 8]


In [43]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)


In [44]:
#### 32. Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_4454/1124167820.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [46]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)



yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2026-06-15 2026-06-16 2026-06-17


In [47]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [48]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [50]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 5. 6. 9. 3. 6. 1. 2. 0. 6.]
[0. 5. 6. 9. 3. 6. 1. 2. 0. 6.]
[0. 5. 6. 9. 3. 6. 1. 2. 0. 6.]
[0 5 6 9 3 6 1 2 0 6]
[0. 5. 6. 9. 3. 6. 1. 2. 0. 6.]


In [3]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array
import numpy as np
def generator():
  for val in range(10):
    yield val
gen=np.fromiter(generator(),dtype=float,count=-1)
gen

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector=np.linspace(0,1,12,endpoint=True)[1:]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091,
       1.        ])

In [13]:
#### 40. Create a random vector of size 10 and sort it
arr=np.random.random(10)
arr.sort()
arr

array([0.02475837, 0.13249982, 0.17453484, 0.18735222, 0.34218054,
       0.51957608, 0.81364838, 0.87866992, 0.90630879, 0.92334013])

In [14]:
#### 41. How to sum a small array faster than np.sum?
a=[1,2,2,3,4]
b=np.sum(a)


np.int64(12)

In [16]:
#faster
np.add.reduce(a)

np.int64(12)

In [17]:
#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [19]:
A,B

(array([1, 0, 1, 1, 0]), array([1, 0, 0, 0, 1]))

In [24]:
eql=np.allclose(A,B)
eql

True

In [26]:
#### 43. Make an array immutable (read-only) (★★☆)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [27]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

# Create a 10x2 matrix with random Cartesian coordinates (x, y)
Z = np.random.random((10,2))

# Separate the x and y coordinates into individual arrays
X, Y = Z[:,0], Z[:,1] # X gets the first column, Y gets the second column

# Calculate the radial distance (R) using the Pythagorean theorem: R = sqrt(x^2 + y^2)
R = np.sqrt(X**2 + Y**2)

# Calculate the angular coordinate (T, or theta) using arctan2.
# arctan2 handles all four quadrants correctly, returning an angle in radians.
T = np.arctan2(Y, X)

# Print the calculated radial distances
print(R)
# Print the calculated angular coordinates (in radians)
print(T)

[0.89708117 0.65595046 0.93184627 0.76907938 1.23107864 0.80927685
 1.19184122 0.93694948 0.98909771 1.00167401]
[1.25714527 0.69929151 0.47876078 1.35867224 0.68740336 0.28553296
 0.94417131 0.24274991 0.74681522 0.32405557]


In [33]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

Z = np.random.random(10)
# m=Z.max() # This stores the maximum *value*, not its index
Z[Z.argmax()] = 0 # Use Z.argmax() to get the index of the maximum value
print(Z)

[0.         0.04504133 0.61183298 0.30536166 0.55143254 0.34881357
 0.46691681 0.44370868 0.07753048 0.34748917]


In [34]:

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [35]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [36]:
#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [37]:
#### 49. How to print all the values of an array? (★★☆)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

45
